version: "3.8"

services:
  database:
      image: 'mysql'
      platform: linux/amd64
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: main
      ports:
          - '3306'
  bdd:
      depends_on:
          - database
      image: phpmyadmin
      restart: always
      ports:
          - 8080:80
      environment:
          PMA_HOST: database
  www:
    build: ''
    container_name: www_symfony
    ports:
      - "8741:80"
    volumes:
        - ./php/vhosts:/etc/apache2/sites-enabled
        - ./:/var/www
    restart: always
    networks:
        - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_symfony
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev
      
networks:
  dev:

volumes:
  db-data:

